const lessons=[
{id:'fundamentals',section:'foundation',t:'What Is Witchcraft?',i:'🌿',d:'Build a vocabulary before you build a practice.',concepts:[['Witchcraft','A broad term used for many historical and contemporary magical or ritual practices.'],['Folklore','Beliefs, stories, customs, and traditions passed through communities.'],['Correspondence','A symbolic association between an object, color, plant, season, or idea and an intention.']],activity:'Write three things you want to learn and one question you still have. Do not worry about having the “right” answer.',source:'Institute of Historical Research — Researching the History of Witchcraft and Magic',url:'https://www.history.ac.uk/news-events/events/ihr-events-archive/researching-history-witchcraft-magic',quiz:['Which statement best describes a correspondence?',['A symbolic association','A scientific law','A mineral formula','A holiday'],0]},
{id:'ethics',section:'foundation',t:'Ethics, Intention & Responsibility',i:'🕯️',d:'Learn how practitioners think about intention, consent, boundaries, and responsibility.',concepts:[['Intention','The purpose or meaning a practitioner gives to a working or ritual.'],['Consent','A useful ethical principle when another person could be affected by your actions.'],['Reflection','Recording what you intended, what you experienced, and what you learned.']],activity:'Create your own three-part practice ethic. Example: respect, consent, and curiosity. Explain why each matters.',source:'Pew Research Center — Religion and spirituality resources',url:'https://www.pewresearch.org/religion/',quiz:['Why can recording your intention be useful?',['It makes a practice scientifically proven','It helps you evaluate your own practice and assumptions','It guarantees a result','It replaces research'],1]},
{id:'history-basics',section:'history',t:'A Short History of Magic & Witchcraft',i:'📜',d:'Separate ancient evidence, medieval ideas, early modern witch trials, and modern reconstruction.',concepts:[['Ancient worlds','Magic and religion overlapped in many ancient societies, but practices differed by place and period.'],['Witch trials','Early modern European witch trials were shaped by law, religion, social conflict, and local circumstances.'],['Modern practice','Contemporary witchcraft includes traditions that developed or were reconstructed in the 19th and 20th centuries.']],activity:'Make a timeline with four entries: an ancient magical practice, the early modern witch trials, a modern Pagan movement, and a contemporary practice. Cite one source for each.',source:'Encyclopaedia Britannica — Witchcraft',url:'https://www.britannica.com/topic/witchcraft',quiz:['Why is it misleading to treat modern witchcraft as one unchanged ancient tradition?',['Practices and meanings changed across cultures and time','Ancient people did not use symbols','History has no sources','Modern practitioners all agree'],0]},
{id:'folk',section:'history',t:'Folk Magic & Living Traditions',i:'🌾',d:'Explore household customs, charms, healing traditions, and regional folklore without flattening cultures into one “witchcraft” category.',concepts:[['Folk practice','Community traditions can include charms, blessings, healing customs, protective objects, and divination.'],['Regional context','The same plant, charm, or custom can have different meanings in different communities.'],['Respect','Some traditions are tied to specific communities and should be studied with cultural context rather than copied casually.']],activity:'Choose one regional folk practice to research. Record where it comes from, who practiced it, when it was documented, and how it is understood today.',source:'Library of Congress — Folklife resources',url:'https://www.loc.gov/collections/american-folklife-center-collections/',quiz:['What should you do before copying a culturally specific practice?',['Ignore its history','Research its community and context','Assume all traditions are interchangeable','Call it ancient'],1]},
{id:'elements',section:'practice',t:'The Elements',i:'🔥',d:'Study the symbolic language of earth, air, fire, water, and—within some modern systems—spirit.',concepts:[['Symbolic language','Elements can act as a framework for describing qualities such as stability, movement, transformation, and emotion.'],['Tradition matters','Element systems vary. There is no single universal correspondence chart.'],['Practice','A practitioner may use an element symbol in meditation, ritual design, or reflection.']],activity:'Make your own five-element chart. For every element, choose one quality, one color, and one object, then write where your association came from.',source:'Encyclopaedia Britannica — Classical elements',url:'https://www.britannica.com/science/classical-element',quiz:['Are elemental correspondences universal?',['Yes, every tradition uses the same chart','No, associations vary by tradition','Only science determines them','Only one element exists'],1]},
{id:'cleansing',section:'practice',t:'Cleansing, Grounding & Sacred Space',i:'🫧',d:'Explore symbolic cleansing and grounding practices while keeping the practical side safe.',concepts:[['Cleansing','A ritual concept for removing unwanted symbolism, atmosphere, or influence.'],['Grounding','Often uses attention, breathing, sensory awareness, or visualization to feel centered.'],['Sacred space','A deliberately marked place used for reflection, ritual, prayer, or focused practice.']],activity:'Design a five-minute grounding routine using only breath, sensory awareness, and visualization. Write down what you notice before and after.',source:'NCCIH — Meditation and mindfulness',url:'https://www.nccih.nih.gov/health/meditation-and-mindfulness-effectiveness-and-safety',quiz:['Which is a low-risk grounding exercise?',['Controlled breathing and sensory awareness','Ingesting an unknown herb','Applying essential oil without checking safety','Burning a random substance indoors'],0]},
{id:'protection',section:'practice',t:'Protection & Boundaries',i:'🛡️',d:'Study protective charms, wards, boundaries, and the psychology of ritual without presenting spiritual claims as medical fact.',concepts:[['Protection','Traditional charms, amulets, wards, circles, and spoken formulas can symbolize safety or boundaries.'],['Boundary','A ritual boundary can represent what you welcome and what you do not.'],['Amulet','A physical object may carry protective meaning in a cultural or personal context.']],activity:'Create a symbolic protection design using only shapes and colors. Explain what each part represents and which tradition inspired it.',source:'British Museum — Amulets and protective objects',url:'https://www.britishmuseum.org/collection',quiz:['What is an amulet in many historical contexts?',['A protective or meaningful object','A scientific instrument','A type of herb','A calendar'],0]},
{id:'sigils',section:'practice',t:'Sigils & Symbol Design',i:'🔮',d:'Learn how modern practitioners use symbols to represent an intention.',concepts:[['Symbol','A visual mark that represents an idea, concept, or intention.'],['Intention','The goal or meaning attached to a symbol or working.'],['Design','Shape, repetition, geometry, and personal meaning can all influence a sigil.']],activity:'Design a non-harmful study or creativity sigil. Record what every visual element represents, then revisit it a week later.',source:'Institute of Historical Research — Magic and occult research',url:'https://www.history.ac.uk/news-events/events/ihr-events-archive/researching-history-witchcraft-magic',quiz:['What makes a sigil useful as a study exercise?',['Its symbolism gives you a way to explore intention','It is guaranteed to change reality','It must follow one universal design','It requires a rare material'],0]},
{id:'crystals',section:'practice',t:'Crystals, Stones & Evidence',i:'💎',d:'Study mineral facts and spiritual symbolism as two different kinds of information.',concepts:[['Geology','Minerals have measurable physical and chemical properties.'],['Folklore','Cultures and modern spiritual communities may assign symbolic meanings to stones.'],['Evidence','Spiritual claims about healing should not be confused with established medical evidence.']],activity:'Pick one stone. Record its mineral facts, historical or cultural uses, modern spiritual associations, and what evidence exists for health claims.',source:'PubMed — 2025 randomized study of crystal effects and anxiety',url:'https://pubmed.ncbi.nlm.nih.gov/40855750/',quiz:['What did the 2025 randomized crystal study report?',['Crystals cured anxiety','Effects exceeded placebo','No specific anxiolytic effect beyond placebo was demonstrated','All crystals are dangerous'],2]},
{id:'herbs',section:'practice',t:'Herbs, Plants & Safety',i:'🌱',d:'Combine plant folklore with real botanical identification and safety research.',concepts:[['Botany','Identify the actual plant species before assuming what something is.'],['Folklore','Plants can carry symbolic meanings that vary by culture and tradition.'],['Safety','Symbolic or traditional use does not automatically mean a plant is edible, medicinal, or safe.']],activity:'Build a research card for rosemary, lavender, or mint: scientific name, family, habitat, historical uses, folklore, and safety notes.',source:'National Center for Complementary and Integrative Health',url:'https://www.nccih.nih.gov/health/herbsataglance',quiz:['What should come first when working with an unfamiliar plant?',['Identify it and check reliable safety information','Taste it','Assume it is harmless','Use it in a spell immediately'],0]},
{id:'moon',section:'practice',t:'Moon Cycles & Seasonal Practice',i:'🌙',d:'Explore the moon and seasonal calendar as symbolic frameworks used in modern witchcraft.',concepts:[['Lunar cycle','The visible phases of the moon form a repeating astronomical cycle.'],['Seasonal practice','Many modern practitioners use solstices, equinoxes, and seasonal themes to structure reflection.'],['Modern framework','The Wheel of the Year is a modern Pagan/Wiccan framework rather than an unchanged ancient calendar.']],activity:'Create a moon or seasonal journal page. Record the date, visible moon phase, season, your intention, and a short reflection.',source:'NASA — Moon phases and lunar science',url:'https://science.nasa.gov/moon/moon-phases/',quiz:['What is the Wheel of the Year best described as?',['A modern Pagan/Wiccan seasonal framework','A geological system','A scientific lunar calendar','A crystal classification'],0]}
];

const nav=document.getElementById('nav'), foundation=document.getElementById('foundationLessons'), history=document.getElementById('historyLessons'), practice=document.getElementById('practiceLessons'), sources=document.getElementById('sources');
let data=JSON.parse(localStorage.getItem('moonlit-v3')||'{"done":{},"notes":{},"scores":{},"journal":"","streak":0,"last":""}');
const today=new Date().toISOString().slice(0,10);
if(data.last!==today){const yesterday=new Date(Date.now()-86400000).toISOString().slice(0,10);data.streak=data.last===yesterday?(data.streak||0)+1:1;data.last=today;localStorage.setItem('moonlit-v3',JSON.stringify(data));}
function persist(){localStorage.setItem('moonlit-v3',JSON.stringify(data));renderStats();}
function toast(msg='Saved ✓'){const el=document.getElementById('toast');el.textContent=msg;el.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>el.classList.remove('show'),1300)}
function renderStats(){const done=Object.values(data.done).filter(Boolean).length;const answered=Object.values(data.scores);const correct=answered.filter(Boolean).length;const pct=answered.length?Math.round(correct/answered.length*100):0;const progress=Math.round(done/lessons.length*100);document.getElementById('lessonStat').textContent=`${done}/${lessons.length} lessons`;document.getElementById('quizStat').textContent=`${pct}% quiz accuracy`;document.getElementById('noteStat').textContent=`${Object.values(data.notes).filter(v=>v&&v.trim()).length} notes`;document.getElementById('progressLabel').textContent=progress+'%';document.getElementById('progressBar').style.width=progress+'%';document.getElementById('sideProgress').style.width=progress+'%';document.getElementById('sideProgressText').textContent=progress+'% complete';document.querySelectorAll('.lesson-card').forEach(card=>{const id=card.dataset.id;const doneState=!!data.done[id];card.classList.toggle('done',doneState);const status=card.querySelector('.lesson-status');if(status)status.textContent=doneState?'✓ Completed':'Not started';const btn=card.querySelector('.complete-btn');if(btn)btn.textContent=doneState?'Completed ✓':'Mark complete';const note=card.querySelector('.lesson-note');if(note)note.value=data.notes[id]||''});}
function makeLesson(l,n){const el=document.createElement('article');el.className='lesson-card';el.dataset.id=l.id;el.id=l.id;el.innerHTML=`<div class="lesson-head"><div class="lesson-num">${String(n+1).padStart(2,'0')}</div><div><span class="lesson-icon">${l.i}</span><h3>${l.t}</h3><p>${l.d}</p></div><span class="lesson-status">Not started</span></div><div class="lesson-body"><div class="concept-grid">${l.concepts.map(c=>`<div class="concept"><b>${c[0]}</b><p>${c[1]}</p></div>`).join('')}</div><div class="lesson-detail"><div class="activity"><strong>📝 Study activity</strong><p>${l.activity}</p><textarea class="lesson-note" data-note="${l.id}" placeholder="Write your notes here…"></textarea><div class="lesson-actions"><button class="small-btn save-note" data-save="${l.id}">Save note</button><button class="small-btn complete-btn" data-complete="${l.id}">Mark complete</button></div></div>${l.quiz?`<div class="activity quiz"><strong>🧠 Knowledge check</strong><p><b>${l.quiz[0]}</b></p>${l.quiz[1].map((x,i)=>`<button class="option" data-q="${l.id}" data-a="${i}">${x}</button>`).join('')}<p class="quiz-result" data-result="${l.id}"></p></div>`:''}</div></div>`;return el;}
lessons.forEach((l,n)=>{const container=l.section==='foundation'?foundation:l.section==='history'?history:practice;container.appendChild(makeLesson(l,n));const s=document.createElement('div');s.className='source';s.dataset.search=(l.t+' '+l.d+' '+l.source).toLowerCase();s.innerHTML=`<b>${l.i} ${l.t}</b><small>${l.source}</small><a href="${l.url}" target="_blank" rel="noopener">Open source →</a>`;sources.appendChild(s);});
renderStats();
document.addEventListener('click',e=>{const head=e.target.closest('.lesson-head');if(head){head.parentElement.classList.toggle('open');return}const complete=e.target.closest('[data-complete]');if(complete){const id=complete.dataset.complete;data.done[id]=!data.done[id];persist();toast(data.done[id]?'Lesson completed ✦':'Lesson reopened');return}const save=e.target.closest('[data-save]');if(save){const id=save.dataset.save;const area=document.querySelector(`[data-note="${id}"]`);data.notes[id]=area.value;persist();toast('Note saved ✓');return}const option=e.target.closest('.option');if(option){const id=option.dataset.q;if(data.scores[id]!==undefined)return;const lesson=lessons.find(x=>x.id===id);const answer=Number(option.dataset.a);const correct=answer===lesson.quiz[2];data.scores[id]=correct;option.parentElement.querySelectorAll('.option').forEach((b,i)=>{if(i===lesson.quiz[2])b.classList.add('correct');else if(i===answer)b.classList.add('wrong')});option.parentElement.querySelector('[data-result]').textContent=correct?'Correct — keep going ✦':'Not quite. The highlighted answer is the one supported by the lesson.';persist();}});

document.getElementById('continueBtn').onclick=()=>{const next=lessons.find(l=>!data.done[l.id]);const target=document.getElementById(next?next.id:'foundations');if(next){target.classList.add('open');target.scrollIntoView({behavior:'smooth',block:'center'});}else target.scrollIntoView({behavior:'smooth'});};
document.getElementById('themeBtn').onclick=()=>{document.body.classList.toggle('light');localStorage.setItem('moonlit-theme',document.body.classList.contains('light')?'light':'dark');};
if(localStorage.getItem('moonlit-theme')==='light')document.body.classList.add('light');
document.getElementById('resetBtn').onclick=()=>{if(confirm('Reset all lessons, quizzes, and notes?')){localStorage.removeItem('moonlit-v3');location.reload();}};
const journal=document.getElementById('journalInput');journal.value=data.journal||'';document.getElementById('journalSave').onclick=()=>{data.journal=journal.value;persist();toast('Grimoire entry saved ✓');};
document.getElementById('searchInput').addEventListener('input',e=>{const q=e.target.value.toLowerCase().trim();document.querySelectorAll('.source').forEach(s=>s.hidden=q&&!s.dataset.search.includes(q));});
document.getElementById('mobileMenu').onclick=()=>document.getElementById('sidebar').classList.toggle('open');
document.querySelectorAll('nav a').forEach(a=>a.addEventListener('click',()=>document.getElementById('sidebar').classList.remove('open')));
