const lessons=[
{id:'fundamentals',t:'Fundamentals',i:'🌿',d:'Understand the vocabulary and major categories before learning specific practices.',concepts:[['Witchcraft','A broad term covering many historical and modern practices.'],['Folklore','Stories, beliefs, customs, and traditions passed through communities.'],['Correspondence','A symbolic association between an object, color, plant, season, or idea and an intention.']],activity:'Write 3 things you want to learn about witchcraft and one question you still have.',source:'Researching the history of witchcraft and magic — Institute of Historical Research',url:'https://www.history.ac.uk/news-events/events/ihr-events-archive/researching-history-witchcraft-magic'},
{id:'protection',t:'Protection & Cleansing',i:'🛡️',d:'Study protection as a symbolic practice involving boundaries, ritual, and cultural tradition.',concepts:[['Protection','Traditional charms, wards, circles, and symbolic boundaries.'],['Cleansing','Symbolic removal of unwanted influences; practices vary widely.'],['Grounding','A mindfulness/visualization practice used to feel centered.']],activity:'Create a symbolic protection design using only shapes and colors. Explain what each part means.',source:'British Museum — ritual/amulet collections',url:'https://www.britishmuseum.org/collection/object/H_1941-1208-1'},
{id:'auras',t:'Auras & Energy',i:'✨',d:'Explore aura symbolism while distinguishing spiritual interpretations from scientific measurements.',concepts:[['Aura','In esoteric traditions, an aura is described as a subtle field around a person.'],['Visualization','Using imagination to represent an idea or intention.'],['Evidence','Aura colors are not established scientific measurements of personality or health.']],activity:'Choose 2 colors and journal what they symbolize to you. Compare your meanings with two traditions you research.',source:'Institute of Historical Research — magic and occult research resources',url:'https://www.history.ac.uk/news-events/events/ihr-events-archive/researching-history-witchcraft-magic'},
{id:'sigils',t:'Sigils',i:'🔮',d:'Learn how symbols can represent an intention and how modern sigil practices developed.',concepts:[['Symbol','An image or mark that represents an idea.'],['Intention','The goal or meaning you associate with a ritual or symbol.'],['Design','Shape, repetition, geometry, and personal meaning can all matter.']],activity:'Design a non-harmful study or creativity sigil. Record what every visual element represents.',source:'Institute of Historical Research — magic and modern paganism resources',url:'https://www.history.ac.uk/news-events/events/ihr-events-archive/researching-history-witchcraft-magic'},
{id:'jars',t:'Spell Jars',i:'🫙',d:'Study spell jars as a modern symbolic format for combining objects and intentions.',concepts:[['Container','A physical object can serve as a reminder of an intention.'],['Correspondences','Ingredients are often chosen for traditional symbolic meanings.'],['Safety','Do not ingest or apply unknown mixtures; keep projects symbolic and safe.']],activity:'Plan a paper-only “spell jar”: draw the container and label 5 symbolic ingredients and their meanings.',source:'Institute of Historical Research — magic and occult collections',url:'https://www.history.ac.uk/news-events/events/ihr-events-archive/researching-history-witchcraft-magic'},
{id:'colors',t:'Color Magic',i:'🎨',d:'Compare common color correspondences and investigate how meanings vary across traditions.',concepts:[['Blue','Often associated with peace, communication, water, or calm.'],['Green','Often associated with nature, growth, prosperity, or healing symbolism.'],['Teal','A modern design-friendly blend that can symbolize balance, water, calm, and renewal.']],activity:'Make your own 8-color correspondence chart. Add a column for “source/tradition” rather than treating meanings as universal.',source:'Institute of Historical Research — historical study of magic and modern paganism',url:'https://www.history.ac.uk/news-events/events/ihr-events-archive/researching-history-witchcraft-magic'},
{id:'crystals',t:'Crystals & Stones',i:'💎',d:'Study mineral properties and the cultural history of crystal symbolism separately from claims of supernatural healing.',concepts:[['Geology','Crystals are minerals or mineral-like materials with physical properties.'],['Folklore','Different cultures and modern spiritual communities assign symbolic meanings to stones.'],['Evidence','A 2025 randomized study of 138 adults found crystal effects on anxiety did not exceed placebo effects.']],activity:'Pick one stone. Record its mineral/geological facts, historical uses, modern spiritual associations, and what evidence exists for health claims.',source:'Escolà-Gascón et al., CNS Spectrums (2025)',url:'https://pubmed.ncbi.nlm.nih.gov/40855750/'},
{id:'herbs',t:'Herbs & Plants',i:'🌱',d:'Learn plant folklore alongside botany and responsible handling.',concepts:[['Folklore','Plants can carry symbolic meanings in different traditions.'],['Botany','Identify the actual plant before assuming what something is.'],['Safety','Magical symbolism does not determine whether a plant is edible or safe.']],activity:'Build a research card for rosemary, lavender, or mint: scientific name, plant family, historical uses, folklore, and safety notes.',source:'British Museum — historical objects connected with folk healing and charms',url:'https://www.britishmuseum.org/collection/object/H_1941-1208-1'},
{id:'holidays',t:'Holidays & the Wheel of the Year',i:'🗓️',d:'Study the eight-observance framework commonly used in modern Wiccan and Neo-Pagan practice.',concepts:[['Solar festivals','Solstices and equinoxes mark astronomical seasonal points.'],['Seasonal festivals','Imbolc, Beltane, Lughnasadh/Lammas, and Samhain are commonly included.'],['Modern framework','The present-day Wheel of the Year developed through modern Pagan/Wiccan traditions rather than existing unchanged since antiquity.']],activity:'Make a timeline of the eight observances. For each, separate “historical evidence” from “modern practice.”',source:'World History Encyclopedia — Wheel of the Year',url:'https://www.worldhistory.org/Wheel_of_the_Year/'},
{id:'baneful',t:'Jinxes, Hexes & Baneful Magic',i:'🌀',d:'Learn the vocabulary and history while keeping practical study focused on non-harmful work.',concepts:[['Jinx','A term commonly used for a minor or general harmful magical influence.'],['Hex','A term for harmful or hostile magic in some traditions.'],['Banishment','A ritual concept focused on separation or removal rather than retaliation.']],activity:'Compare the words jinx, hex, curse, binding, and banishment in a glossary. Cite a source for each definition.',source:'Institute of Historical Research — witchcraft and magic research resources',url:'https://www.history.ac.uk/news-events/events/ihr-events-archive/researching-history-witchcraft-magic'}];

const qs=[
['Which statement best describes a correspondence?',['A symbolic association','A scientific law','A mineral formula','A holiday'],0],
['What does the 2025 crystal study suggest?',['Crystals cured anxiety','Results exceeded placebo effects','No specific anxiolytic effect beyond placebo was demonstrated','Crystals are dangerous'],2],
['What is the Wheel of the Year?',['A modern Pagan/Wiccan seasonal framework','A geology system','A type of crystal','A scientific calendar'],0],
['Why should color meanings be labeled by tradition?',['Meanings vary across traditions','Colors have no symbolism','Only one tradition exists','Science assigns every magical color'],0]
];

const nav=document.getElementById('nav'), area=document.getElementById('lessonArea'), sources=document.getElementById('sources');
lessons.forEach((l,n)=>{let a=document.createElement('a');a.href='#'+l.id;a.textContent=`${l.i} ${n+1}. ${l.t}`;nav.appendChild(a);
let sec=document.createElement('article');sec.className='lesson';sec.id=l.id;sec.innerHTML=`<div class="eyebrow">LESSON ${String(n+1).padStart(2,'0')}</div><h2>${l.i} ${l.t}</h2><p class="meta">${l.d}</p><div class="lesson-grid"><div><h3>Core concepts</h3><div class="concepts">${l.concepts.map(x=>`<div class="concept"><b>${x[0]}</b>${x[1]}</div>`).join('')}</div><button class="complete" data-id="${l.id}">Mark complete</button></div><div class="activity"><b>📝 Study activity</b><p>${l.activity}</p><textarea data-note="${l.id}" placeholder="Write your notes here..."></textarea><button class="save" data-save="${l.id}">Save note</button></div></div>`;
if(n<qs.length){let q=qs[n];sec.innerHTML+=`<div class="quiz"><h3>🧠 Quick quiz</h3><p><b>${q[0]}</b></p>${q[1].map((x,i)=>`<button class="option" data-q="${n}" data-a="${i}">${x}</button>`).join('')}<p class="quiz-result" id="qr${n}"></p></div>`}area.appendChild(sec);
let s=document.createElement('div');s.className='source';s.innerHTML=`<b>${l.source}</b><small>Lesson ${n+1} research link</small><a href="${l.url}" target="_blank" rel="noopener">Open source →</a>`;sources.appendChild(s);});

let data=JSON.parse(localStorage.getItem('moonlit-v2')||'{"done":{},"notes":{},"scores":{},"streak":0,"last":""}');
function save(){localStorage.setItem('moonlit-v2',JSON.stringify(data));renderStats()}
function renderStats(){let done=Object.values(data.done).filter(Boolean).length, notes=Object.values(data.notes).filter(x=>x&&x.trim()).length, answered=Object.values(data.scores), correct=answered.filter(x=>x).length, pct=answered.length?Math.round(correct/answered.length*100):0;document.getElementById('lessonStat').textContent=`${done}/${lessons.length}`;document.getElementById('quizStat').textContent=pct+'%';document.getElementById('noteStat').textContent=notes;document.getElementById('streakStat').textContent=data.streak+' day'+(data.streak===1?'':'s');document.getElementById('progressLabel').textContent=Math.round(done/lessons.length*100)+'%';document.getElementById('progressBar').style.width=Math.round(done/lessons.length*100)+'%';document.querySelectorAll('.complete').forEach(b=>{let d=data.done[b.dataset.id];b.classList.toggle('done',!!d);b.textContent=d?'✓ Completed':'Mark complete'});document.querySelectorAll('[data-note]').forEach(t=>t.value=data.notes[t.dataset.note]||'')}
document.addEventListener('click',e=>{if(e.target.matches('.complete')){let id=e.target.dataset.id;data.done[id]=!data.done[id];save()}if(e.target.matches('.save')){let id=e.target.dataset.save;data.notes[id]=document.querySelector(`[data-note="${id}"]`).value;save();e.target.textContent='Saved ✓';setTimeout(()=>e.target.textContent='Save note',900)}if(e.target.matches('.option')){let q=+e.target.dataset.q,a=+e.target.dataset.a;if(data.scores[q]!==undefined)return;data.scores[q]=a===qs[q][2];e.target.parentElement.querySelectorAll('.option').forEach((b,i)=>{if(i===qs[q][2])b.classList.add('correct');else if(i===a)b.classList.add('wrong')});document.getElementById('qr'+q).textContent=a===qs[q][2]?'Correct! ✨':'Not quite — the highlighted answer is correct.';save()}});
document.getElementById('themeBtn').onclick=()=>document.body.classList.toggle('light');
document.getElementById('resetBtn').onclick=()=>{if(confirm('Reset your course progress and notes?')){localStorage.removeItem('moonlit-v2');location.reload()}};
renderStats();